import { createSlice } from "@reduxjs/toolkit"
import { HYDRATE } from "next-redux-wrapper"


const initialState = [
   {id:  0, text:"Все страны", active: true},
   {id:  1, text:"Россия", active: false},
   {id:  2, text:"СССР", active: false},
   {id:  3, text:"США", active: false},
   {id:  4, text:"Франция", active: false},
   {id:  5, text:"Италия", active: false},
   {id:  6, text:"Испания", active: false},
   {id:  7, text:"Великобритания", active: false},
   {id:  8, text:"Германия", active: false},
   {id:  9, text:"Корея Южная", active: false},
    {id: 10, text:"Япония", active: false},
    {id: 11, text:"Австралия", active: false},
    {id: 12, text:"Австрия", active: false},
    {id: 13, text:"Азербайджан", active: false},
    {id: 14, text:"Албания", active: false},
    {id: 15, text:"Алжир", active: false},
    {id: 16, text:"Американские Виргинские острова", active: false},
    {id: 17, text:"Американское Самоа", active: false},
    {id: 18, text:"Ангола", active: false},
    {id: 19, text:"Андорра", active: false},
    {id: 20, text:"Антарктида", active: false},
    {id: 21, text:"Антигуа и Барбуда", active: false},
    {id: 22, text:"Антильские Острова", active: false},
    {id: 23, text:"Аргентина", active: false},
    {id: 24, text:"Армения", active: false},
    {id: 25, text:"Аруба", active: false},
    {id: 26, text:"Афганистан", active: false},
    {id: 27, text:"Багамы", active: false},
    {id: 28, text:"Бангладеш", active: false},
    {id: 29, text:"Барбадос", active: false},
    {id: 30, text:"Бахрейн", active: false},
    {id: 31, text:"Беларусь", active: false},
    {id: 32, text:"Белиз", active: false},
    {id: 33, text:"Бельгия", active: false},
    {id: 34, text:"Бенин", active: false},
    {id: 35, text:"Берег Слоновой кости", active: false},
    {id: 36, text:"Бермуды", active: false},
    {id: 37, text:"Бирма", active: false},
    {id: 38, text:"Болгария", active: false},
    {id: 39, text:"Боливия", active: false},
    {id: 40, text:"Босния", active: false},
    {id: 41, text:"Босния и Герцеговина", active: false},
    {id: 42, text:"Ботсвана", active: false},
    {id: 43, text:"Бразилия", active: false},
    {id: 44, text:"Бруней-Даруссалам", active: false},
    {id: 45, text:"Буркина-Фасо", active: false},
    {id: 46, text:"Бурунди", active: false},
    {id: 47, text:"Бутан", active: false},
    {id: 48, text:"Вануату", active: false},
    {id: 49, text:"Ватикан", active: false},
    {id: 50, text:"Венгрия", active: false},
    {id: 51, text:"Венесуэла", active: false},
    {id: 52, text:"Виргинские Острова", active: false},
    {id: 53, text:"Внешние малые острова США", active: false},
    {id: 54, text:"Вьетнам", active: false},
    {id: 55, text:"Вьетнам Северный", active: false},
    {id: 56, text:"Габон", active: false},
    {id: 57, text:"Гаити", active: false},
    {id: 58, text:"Гайана", active: false},
    {id: 59, text:"Гамбия", active: false},
    {id: 60, text:"Гана", active: false},
    {id: 61, text:"Гваделупа", active: false},
    {id: 62, text:"Гватемала", active: false},
    {id: 63, text:"Гвинея", active: false},
    {id: 64, text:"Гвинея-Бисау", active: false},
    {id: 65, text:"Германия (ГДР)", active: false},
    {id: 66, text:"Германия (ФРГ)", active: false},
    {id: 67, text:"Гибралтар", active: false},
    {id: 68, text:"Гондурас", active: false},
    {id: 69, text:"Гонконг", active: false},
    {id: 70, text:"Гренада", active: false},
    {id: 71, text:"Гренландия", active: false},
    {id: 72, text:"Греция", active: false},
    {id: 73, text:"Грузия", active: false},
    {id: 74, text:"Гуам", active: false},
    {id: 75, text:"Дания", active: false},
    {id: 76, text:"Джибути", active: false},
    {id: 77, text:"Доминика", active: false},
    {id: 78, text:"Доминикана", active: false},
    {id: 79, text:"Египет", active: false},
    {id: 80, text:"Заир", active: false},
    {id: 81, text:"Замбия", active: false},
    {id: 82, text:"Западная Сахара", active: false},
    {id: 83, text:"Зимбабве", active: false},
    {id: 84, text:"Израиль", active: false},
    {id: 85, text:"Индия", active: false},
    {id: 86, text:"Индонезия", active: false},
    {id: 87, text:"Иордания", active: false},
    {id: 88, text:"Ирак", active: false},
    {id: 89, text:"Иран", active: false},
    {id: 90, text:"Ирландия", active: false},
    {id: 91, text:"Исландия", active: false},
    {id: 92, text:"Йемен", active: false},
    {id: 93, text:"Кабо-Верде", active: false},
    {id: 94, text:"Казахстан", active: false},
    {id: 95, text:"Каймановы острова", active: false},
    {id: 96, text:"Камбоджа", active: false},
    {id: 97, text:"Камерун", active: false},
    {id: 98, text:"Канада", active: false},
    {id: 99, text:"Катар", active: false},
    {id:100, text : "Кения", active: false},
    {id:101, text : "Кипр", active: false},
    {id:102, text : "Киргизия", active: false},
    {id:103, text : "Кирибати", active: false},
    {id:104, text : "Китай", active: false},
    {id:105, text : "Колумбия", active: false},
    {id:106, text : "Коморы", active: false},
    {id:107, text : "Конго", active: false},
    {id:108, text : "Конго (ДРК)", active: false},
    {id:109, text : "Корея", active: false},
    {id:110, text : "Корея Северная", active: false},
    {id:111, text : "Косово", active: false},
    {id:112, text : "Коста-Рика", active: false},
    {id:113, text : "Кот-д’Ивуар", active: false},
    {id:114, text : "Куба", active: false},
    {id:115, text : "Кувейт", active: false},
    {id:116, text : "Лаос", active: false},
    {id:117, text : "Латвия", active: false},
    {id:118, text : "Лесото", active: false},
    {id:119, text : "Либерия", active: false},
    {id:120, text : "Ливан", active: false},
    {id:121, text : "Ливия", active: false},
    {id:122, text : "Литва", active: false},
    {id:123, text : "Лихтенштейн", active: false},
    {id:124, text : "Люксембург", active: false},
    {id:125, text : "Маврикий", active: false},
    {id:126, text : "Мавритания", active: false},
    {id:127, text : "Мадагаскар", active: false},
    {id:128, text : "Макао", active: false},
    {id:129, text : "Македония", active: false},
    {id:130, text : "Малави", active: false},
    {id:131, text : "Малайзия", active: false},
    {id:132, text : "Мали", active: false},
    {id:133, text : "Мальдивы", active: false},
    {id:134, text : "Мальта", active: false},
    {id:135, text : "Марокко", active: false},
    {id:136, text : "Мартиника", active: false},
    {id:137, text : "Маршалловы острова", active: false},
    {id:138, text : "Масаи", active: false},
    {id:139, text : "Мексика", active: false},
    {id:140, text : "Мелкие отдаленные острова США", active: false},
    {id:141, text : "Мозамбик", active: false},
    {id:142, text : "Молдова", active: false},
    {id:143, text : "Монако", active: false},
    {id:144, text : "Монголия", active: false},
    {id:145, text : "Монтсеррат", active: false},
    {id:146, text : "Мьянма", active: false},
    {id:147, text : "Намибия", active: false},
    {id:148, text : "Непал", active: false},
    {id:149, text : "Нигер", active: false},
    {id:150, text : "Нигерия", active: false},
    {id:151, text : "Нидерланды", active: false},
    {id:152, text : "Никарагуа", active: false},
    {id:153, text : "Новая Зеландия", active: false},
    {id:154, text : "Новая Каледония", active: false},
    {id:155, text : "Норвегия", active: false},
    {id:156, text : "ОАЭ", active: false},
    {id:157, text : "Оккупированная Палестинская территория", active: false},
    {id:158, text : "Оман", active: false},
    {id:159, text : "Остров Мэн", active: false},
    {id:160, text : "Остров Святой Елены", active: false},
    {id:161, text : "Острова Кука", active: false},
    {id:162, text : "острова Теркс и Кайкос", active: false},
    {id:163, text : "Пакистан", active: false},
    {id:164, text : "Палау", active: false},
    {id:165, text : "Палестина", active: false},
    {id:166, text : "Панама", active: false},
    {id:167, text : "Папуа - Новая Гвинея", active: false},
    {id:168, text : "Парагвай", active: false},
    {id:169, text : "Перу", active: false},
    {id:170, text : "Польша", active: false},
    {id:171, text : "Португалия", active: false},
    {id:172, text : "Пуэрто Рико", active: false},
    {id:173, text : "Реюньон", active: false},
    {id:174, text : "Российская империя", active: false},
    {id:175, text : "Руанда", active: false},
    {id:176, text : "Румыния", active: false},
    {id:177, text : "Сальвадор", active: false},
    {id:178, text : "Самоа", active: false},
    {id:179, text : "Сан-Марино", active: false},
    {id:180, text : "Сан-Томе и Принсипи", active: false},
    {id:181, text : "Саудовская Аравия", active: false},
    {id:182, text : "Свазиленд", active: false},
    {id:183, text : "Северная Македония", active: false},
    {id:184, text : "Сейшельские острова", active: false},
    {id:185, text : "Сенегал", active: false},
    {id:186, text : "Сент-Винсент и Гренадины", active: false},
    {id:187, text : "Сент-Китс и Невис", active: false},
    {id:188, text : "Сент-Люсия ", active: false},
    {id:189, text : "Сербия", active: false},
    {id:190, text : "Сербия и Черногория", active: false},
    {id:191, text : "Сиам", active: false},
    {id:192, text : "Сингапур", active: false},
    {id:193, text : "Сирия", active: false},
    {id:194, text : "Словакия", active: false},
    {id:195, text : "Словения", active: false},
    {id:196, text : "Соломоновы Острова", active: false},
    {id:197, text : "Сомали", active: false},
    {id:198, text : "Судан", active: false},
    {id:199, text : "Суринам", active: false},
    {id: 200, text: "Сьерра-Леоне", active: false},
    {id: 201, text: "Таджикистан", active: false},
    {id: 202, text: "Таиланд", active: false},
    {id: 203, text: "Тайвань", active: false},
    {id: 204, text: "Танзания", active: false},
    {id: 205, text: "Тимор-Лесте", active: false},
    {id: 206, text: "Того", active: false},
    {id: 207, text: "Тонга", active: false},
    {id: 208, text: "Тринидад и Тобаго", active: false},
    {id: 209, text: "Тувалу", active: false},
    {id: 210, text: "Тунис", active: false},
    {id: 211, text: "Туркменистан", active: false},
    {id: 212, text: "Турция", active: false},
    {id: 213, text: "Уганда", active: false},
    {id: 214, text: "Узбекистан", active: false},
    {id: 215, text: "Украина", active: false},
    {id: 216, text: "Уоллис и Футуна", active: false},
    {id: 217, text: "Уругвай", active: false},
    {id: 218, text: "Фарерские острова", active: false},
    {id: 219, text: "Федеративные Штаты Микронезии", active: false},
    {id: 220, text: "Фиджи", active: false},
    {id: 221, text: "Филиппины", active: false},
    {id: 222, text: "Финляндия", active: false},
    {id: 223, text: "Фолклендские острова", active: false},
    {id: 224, text: "Французская Гвиана", active: false},
    {id: 225, text: "Французская Полинезия", active: false},
    {id: 226, text: "Хорватия", active: false},
    {id: 227, text: "ЦАР", active: false},
    {id: 228, text: "Чад", active: false},
    {id: 229, text: "Черногория", active: false},
    {id: 230, text: "Чехия", active: false},
    {id: 231, text: "Чехословакия", active: false},
    {id: 232, text: "Чили", active: false},
    {id: 233, text: "Швейцария", active: false},
    {id: 234, text: "Швеция", active: false},
    {id: 235, text: "Шпицберген и Ян-Майен", active: false},
    {id: 236, text: "Шри-Ланка", active: false},
    {id: 237, text: "Эквадор", active: false},
    {id: 238, text: "Экваториальная Гвинея", active: false},
    {id: 239, text: "Эритрея", active: false},
    {id: 240, text: "Эстония", active: false},
    {id: 241, text: "Эфиопия", active: false},
    {id: 242, text: "ЮАР", active: false},
    {id: 243, text: "Югославия", active: false},
    {id: 244, text: "Югославия (ФР)", active: false},
    {id: 245, text: "Ямайка", active: false},
]


export const FilterCountriesReducer = createSlice({
    name: 'Filter Countries',
    initialState,
    reducers: {

        setFilterCountries(state, action) {
            return state.map(e=>e.id==action.payload.id ? {...e, active: true} : {...e, active: false})
        },

        // extra
        extraReducer: {
            [HYDRATE]: (state,action) => {
                return {
                    ...state,
                    ...action.payload
                }
            }
        }
    }
})

export const {setFilterCountries} = FilterCountriesReducer.actions;
export const filterCountriesState = (state)=>state.FilterCountriesReducer;
export default FilterCountriesReducer.reducer